### ISSUE TITLE
050 boyer_moore_horspool_searcherの使い方で自己言及

### ISSUE THREAD

**Issue by Tan90909090** [EzoeRyou/cpp17book#128]
[boyer_moore_horspool_searcher](https://github.com/EzoeRyou/cpp17book/blob/master/050-cpp17-lib-misc-searchers.md#boyer_moore_horspool_searcher)の節で
> 使い方はboyer_moore_horspool_searcherと変わらない。

と自己言及になっています。
前の節に出てきているboyer_moore_searcherを使った
「使い方はboyer_moore_searcherと変わらない」ではないでしょうか。

**Comment by EzoeRyou** [comment]
直した。
