### ISSUE TITLE
043 memory_allocatorがdo_allocateを2回オーバーライド

### ISSUE THREAD

**Issue by Tan90909090** [EzoeRyou/cpp17book#129]
[標準ライブラリのメモリーリソース](https://github.com/EzoeRyou/cpp17book/blob/master/043-cpp17-lib-memory-resource.md#%E6%A8%99%E6%BA%96%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E3%83%A1%E3%83%A2%E3%83%AA%E3%83%BC%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9)のサンプルで定義しているmemory_allocator中で、do_allocateを2回オーバーライドしています。
```cpp
    virtual void * 
    do_allocate( std::size_t bytes, std::size_t alignment ) override
    {
        std::scoped_lock lock( m ) ; 
        // リンクリストをたどり、十分な大きさの未使用領域を探し、リンクリスト構造体を構築して返す
        // アライメント要求に注意
    }

    virtual void * 
    do_allocate( std::size_t bytes, std::size_t alignment ) override
    {
        std::scoped_lock lock( m ) ;
        // リンクリストから該当する部分を削除
    }
```
後者はdo_deallocateのオーバーライドではないでしょうか。

**Comment by EzoeRyou** [comment]
直した。
