### ISSUE TITLE
027 @= は複合代入演算子だけでなく単純代入演算子も含む？

### ISSUE THREAD

**Issue by Tan90909090** [EzoeRyou/cpp17book#130]
#114 のFixとして@=の説明が入りましたが、現状の文章では複合代入演算子のみ指しているように思います:
> @=の@には文法上許される任意の演算子が入る(+=, -=など)

一方で[P0145R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0145r3.pdf)を読むと次の記述があり、単純代入演算子(simple assignment)も含まれているように思います:
> Assignment expressions are evaluated from right to left. This includes compound assignments.

@=の説明を、「@=は単純代入演算子か、+=などの複合代入演算子を指す」とするのはどうでしょうか？

**Comment by EzoeRyou** [comment]
追加した。
