### ISSUE TITLE
037 std::byteのサンプルコード中の「アルファベットの'l'」コメントが分からない

### ISSUE THREAD

**Issue by Tan90909090** [EzoeRyou/cpp17book#131]
[std::byte](https://github.com/EzoeRyou/cpp17book/blob/master/037-cpp17-core-std-byte.md)のサンプルコード中に、次の1行があります:
```c++
b = static_cast< std::byte >( 0b11110000 ) ; // アルファベットの'l'
```
このコメントを見て2つの解釈が浮かびましたが、どちらも違いました。
1. リテラル中にアルファベットの'l'が現れていることの注意喚起？→数字の'1'と'0'だけが現れているので違う
2. 0b11110000の値がアルファベットの'l'を指している？→'l'のASCIIコード値は0x6Cなので違う

このコメントはどういった意味でしょうか？

**Comment by EzoeRyou** [comment]
わからないので消した。多分適当なクリップボードに入っていた内容を貼り付けてしまったとかではなかろうか。
