### ISSUE TITLE
constexprラムダ式がtemplate中で使えないことを軽く触れておくべきではないか？

### ISSUE THREAD

**Issue by yumetodo** [EzoeRyou/cpp17book#43]
https://github.com/EzoeRyou/cpp17book/blob/fe9ecd31cf918de9a91de74bd02f0f61b6a15353/021-cpp17-core-constexpr-lambda.md

```cpp
#include <type_traits>

int main()
{
    static_assert(true ==std::bool_constant<[](){ return true; }()>{});
}
```

これは違法だが、「コンパイル時定数を必要とする場所で使うことができる」と書いていると使えるのではないかと思ってしまう。

**Comment by tzik** [comment]
これはgccとclangで挙動が違うのですが（gccではエラー、clangではOK）、仕様的にはどちらが正しいでしょう？

**Comment by yumetodo** [comment]
あとSFINAEの文脈では使えない話も必要かもしれない(if constexpr でSFINAEが過去のものになったといえるならともかく)。

**Comment by EzoeRyou** [comment]
これは合法です。

違法なのはテンプレート実引数としてSFINAEでコンセプトもどきとして使う以下のような例。

~~~cpp
template < typename T, bool b = []{ if ( T t ; t.func() ; return true ; }() >
void f() { }
~~~

これを許すとTに依存する任意の式や文を書けるので、実質コンセプトチェックと同等の機能が実現してしまう。

**Comment by EzoeRyou** [comment]
本書はできるだけ簡潔に書くようにしたのでそういう些細な落とし穴は省いたが、書いても差し支えないとは思う。

**Comment by EzoeRyou** [comment]
https://github.com/EzoeRyou/cpp17book/commit/8ef634bcd5bfc92ae2b508c583d6630e70fccefe

入れた。
