### ISSUE TITLE
027 オペランドの評価順序: 言葉遣いの修正

### ISSUE THREAD

**Issue by nekketsuuu** [EzoeRyou/cpp17book#88]
[027-cpp17-core-evaluation-order.md](https://github.com/EzoeRyou/cpp17book/blob/f7082dc079355edb540a21bdb400c1b57a4acb9d/027-cpp17-core-evaluation-order.md) において「a, b, c, dの順番に評価される」と書いてある下のコードブロックには変数 c, d がありません。間違いとは言い切れませんが、奇妙です。

また、この節の最終行付近に

> 関数呼び出しの実引数のオペランドb1, b2, b3の評価順序は未規定のままだ。
> これにより、既存の未定義の挙動となっていたコードの挙動が定まる。

と書かれていますが、「未定義の挙動」は Undefined Behavior と紛らわしいため、上の行と言葉を揃えて「未規定の挙動」とするのは如何でしょうか。

**Comment by akinomyoga** [comment]
この文脈では undefined behavior で良いように思います。unsequenced な二つの式の評価が問題になるのは、一方の副作用が他方に影響を与えるときでしたが、このとき undefined behavior <sup>[[intro.execution]/17](http://eel.is/c++draft/intro.execution#17.sentence-3)</sup> になります。

~~むしろ、実引数の評価順序が「未規定」という方に語弊があるかもしれません。一つの関数呼び出しにおける「実引数同士」の評価については特に記述がないので unsequenced (混ぜて実行できる) と思われる <sup>[[intro.execution]/18](http://eel.is/c++draft/intro.execution#18), [[expr.call]/5](http://eel.is/c++draft/expr.call#5), [[intro.execution]/17](http://eel.is/c++draft/intro.execution#17.sentence-1)</sup> のですが、未規定と書くと indeterminately sequenced (順序づけはあるが未規定 <sup>[[intro.execution]/15](http://eel.is/c++draft/intro.execution#15.sentence-4)</sup>) とも取れます (unsequenced が別の種類の unspecified であるとは規格中に明記はありません)。とは書きつつ、この書籍では深いところには立ち入らずに初心者でも分かるように書くという趣旨がありますので、かように細かいことを気にしても仕方がないかもしれませんが。~~

すみません。撤回します。[[expr.call]/5](http://eel.is/c++draft/expr.call#5.sentence-2) に indeterminately sequenced と書かれていますね。従って、未規定です。

**Comment by akinomyoga** [comment]
## `a.*b` 抜け?
ところで、ここの箇所で挙げられている新しく順序付けられた式に `a.*b` [[expr.mptr.oper]/4](http://eel.is/c++draft/expr.mptr.oper#4.sentence-3) が抜けていませんか?

## `a.b`, `a->b` の評価順序とは?
あと、純粋に疑問なのですが: `a.b` および `a->b` が列挙されていますが、`b` はメンバ名になるので評価も何もない気がします…。さらに規格の対応する部分 <sup>[[expr.ref]](http://eel.is/c++draft/expr.ref)</sup> も探してみましたが sequenced 云々について見つけられませんでした (探し方が甘いだけかもしれませんが)。むしろ「演算子の左側の式が評価される」<sup>[[expr.ref]/1](http://eel.is/c++draft/expr.ref#1.sentence-2)</sup>と書かれています。

**Comment by nekketsuuu** [comment]
@akinomyoga (「未定義の挙動」について) なるほど、確かにそうですね。ご教示ありがとうございます。

**Comment by nekketsuuu** [comment]
あ、すいません、`a, b, c, d` の問題はまだ解決していませんでした。reopen します。

**Comment by akinomyoga** [comment]
Fixed by 4437751737856bac02d9141bd19d8be66a2ce24d
