### ISSUE TITLE
バックスラッシュのエスケープ

### ISSUE THREAD

**Issue by nekketsuuu** [EzoeRyou/cpp17book#94]
073-cpp17-lib-filesystem.md において、[「path : ファイルパス文字列クラス」](https://github.com/EzoeRyou/cpp17book/blob/1916992bb9457d9e64c65171f60243bab515e198/073-cpp17-lib-filesystem.md#path--ファイルパス文字列クラス)の

> 例えばPOSIX互換環境では/が用いられるが、Microsoft Windowsでは\が使われている。

と

> 例えば、Microsoft Windowsでは、ネイティブのファイルパス文字列はディレクトリーの区切り文字にPOSIX準拠の/ではなく\を使っている。

および[「resize」](https://github.com/EzoeRyou/cpp17book/blob/1916992bb9457d9e64c65171f60243bab515e198/073-cpp17-lib-filesystem.md#resize)の

> 増えたデータはnullバイト''でパディングされる。

という3箇所の文においてバックスラッシュが出てきています。これは GFM ではそのまま問題なく表示されていますが、pandoc に通すとエスケープだと判断されてしまい、バックスラッシュ以降の文章が消えてしまっています ([参考](https://ezoeryou.github.io/cpp17book/#path-ファイルパス文字列クラス))。

`\\` とバックスラッシュ自体をエスケープすれば HTML 上は意図通り表示されるようになります。
GitHub 上で .md ファイルを閲覧した場合もちゃんとエスケープが認識されて表示されるようです ([参考: 修正を施したブランチ](https://github.com/nekketsuuu/cpp17book/blob/a00994aac249b96ac8781a19455325c601e344ed/073-cpp17-lib-filesystem.md#path--ファイルパス文字列クラス))。

提案: 地の文の生のバックスラッシュをエスケープするのは如何でしょうか?

**Comment by akinomyoga** [comment]
Note: 前者2つについては #98 で `` `\` `` などのように修正されましたね (3つめの `'\0'` は未修正)

**Comment by yumetodo** [comment]
@nekketsuuu `\0`の件についてもPull Requestを投げました。( #107 )

単なるエスケープよりMarkdown, HTML上での可読性があるcode tagを利用しています。

**Comment by nekketsuuu** [comment]
他のインラインコード部分が code tag でマークアップされていないのにバックスラッシュ周りだけ code tag にするのも一貫性が無いかなあと思いエスケーピングを提案しましたが、code tag にした PR がマージされたので、`\0` についても code tag にするのが良さそうですね。ありがとうございます。

**Comment by nekketsuuu** [comment]
どちらの PR もマージされたのでクローズします。@yumetodo さん、ありがとうございました。
